Feat. send current DB state to App and apply bg-color to chosen one
Team-Dataface/DataFace-client pull request #24
Opened 2023-07-25 15:00 UTC by Youjin-cmd

### [[FE] 좌측 사이드바](https://www.notion.so/FE-63ee0bf80da446c1bb50f1cddf1243ff?pvs=4)

### description

- DB 이름을 눌렀을 시 DB의 id를 App의 state로 올립니다.
const [currentDBId, setCurrentDBId] = useState("");
currentDBId state를 작업하실 컴포넌트에서 받아와서 useQuery를 통해 캐시에 필요 정보를 요청하면 됩니다~!
-  조건부 동적 className설정을 통해서 현재 보고있는 DB와 일치할 경우 노란 배경색이 들어옵니다.

### PR 전 확인사항

- [X] 가장 최신 브랜치를 pull했습니다.
- [X] base 브랜치명을 확인했습니다.(Front, Backend, feature ...)
- [X] 코드 컨벤션을 모두 지켰습니다.
- [X] 적절한 라벨이 있습니다.
- [X] assignee가 있습니다.

![Jul-25-2023 23-23-13](https://github.com/Team-Dataface/DataFace-client/assets/83858724/9e417df2-e297-4ded-86f3-b700ac980e3b)

2023-07-25 16:36 UTC, darren-kk requested changes
유진님 구현해주신 로직중에 리팩토링이 있으면 좋지 않을까 하는 부분 제안 드렸습니다! 
덕분에 너무나 멋지고 기능적인 사이드바가 생겼네요!! 
감사합니다

2023-07-25 16:36 UTC, darren-kk commented on src/app/App.jsx
> +        ) : null}
각각 헤더와 컴포넌트 들이 이제 필요한 DB id도 받을수 있네요! 유진님 최고!

2023-07-25 16:36 UTC, darren-kk commented on src/components/Modals/CreateDBModal.jsx
> +      queryClient.refetchQueries(["userDbList"]);
`queryClient`를 통해 mutate 일어났을때 Query들이 refetch 되게 하여 실시간으로 수정되는 부분 너무 좋습니다!

2023-07-25 16:36 UTC, darren-kk commented on src/components/Sidebar.jsx
>      },
```suggestion
const { data, isLoading } = useQuery(["userDbList"], getDatabaseList, {
    enabled: !!user,
    onSuccess: result => {
      setCurrentDBId(result.data.databases[0]._id);
    },
    onFailure: () => {
      console.log("sending user to errorpage");
    },
    refetchOnWindowFocus: false,
  });
```

유진님 사용자 경험을 생각하여 다른 윈도우 이동시에도 컴포넌트가 계속 focusing 하고 있는 database Id 를 기억할 수 있게 하기 위하여 useEffect와 firstDatabaseId 라는 state를 추가하여 기능 구현 해주신 점 인상 깊네요!! 
다만 실질적으로 sideEffect를 관리하는것이 아닌데 useEffect를 사용하는것은 약간의 로직적인 트릭..? 같은 느낌이 들어 다음과 같이 리팩토링 해보았습니다! 

useQuery의 옵션중 refetchOnWindowFocus 라는 옵션을 꺼주는것으로 윈도우를 이동해도 useQuery는 서버에 fetch 요청을 보내지 않도록 해줄수가 있는데요! 
더하여 firstDatabaseId 라는 state도 사용하지 않을 수 있었습니다! 
이를 통해 고민하던 부분의 해결이 가능했습니다! 
추가적으로 onSuccess시에 data 라는 변수가 undefined 로 나오는 issue가 있어 result 라는 인자로 아이디 값을 업데이트 하도록 변경 했습니다! 
이 부분 한번 고민 해주시면 감사하겠습니다! :)

2023-07-25 16:36 UTC, darren-kk commented on src/components/Sidebar.jsx
> +            ${isActive(element._id) ? "bg-yellow" : ""}
동적인 값으로 tailwind에 classname을 주셨군요!! 👍 👍 👍

2023-07-25 16:43 UTC, Youjin-cmd commented on src/components/Sidebar.jsx
>      },
네 최초에 단 한번만 실행되어야 하는 로직을 만들기 위해 머리를 싸맨 결과입니다..! ㅠ dependency로 주는 값을 [0]번째의 id state로 정해줘서, 예를 들어 유저가 맨 처음 db를 삭제하여 [0]번째가 바뀌었을 때만 useEffect내부 setState함수가 돌도록 작성해보았어요. 이 모든게 windowFocus로 인한 refetch문제 때문였구요.
그나저나 refetchOnWindowFocus: false,를 써봤다가 잘 안되서 지우고 다른 방법을 찾으며 시간을 많이 썼는데. onFailure 아래에 위치하면 잘 되나봅니다!!
순서문제였을 수도 있겠다는 깨달음을 얻었네요...

적용해보니 잘 되네요 감사합니다.
리팩토링해서 다시 push하겠습니다!

2023-07-26 06:07 UTC, 1eokim approved these changes
유진님 사이드바 디자인하시느라 수고많으셨습니다!

특히, `currentDBId` 상태를 사용해서 id 중심으로 하위 컴포넌트들이 작동할 수 있는 토대를 만들어주신 점 정말 최고입니다 👍

2023-07-26 06:08 UTC, darren-kk approved these changes

2023-07-26 06:08 UTC, merged